### ISSUE TITLE
Hi Friend: ENOENT: no such file or directory, Router.js.map

### ISSUE THREAD

**Issue by numerized** [ionic2-ninja/emiya-ionic2-router#1]
Hello here, 

Looks promising on the demo, but cannot use it because I got this :

Uncaught Error: Module build failed: Error: ENOENT: no such file or directory, open '/Users/numerized/Work/00_Github/vitapp-ionic2-couch/node_modules/emiya-ionic2-router/Router.js.map'
    at Error (native)
    at Error (native)
    at Object.<anonymous> (http://localhost:8101/build/main.js:181433:7)
    at __webpack_require__ (http://localhost:8101/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8101/build/main.js:181440:66)
    at __webpack_require__ (http://localhost:8101/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8101/build/main.js:123996:78)
    at __webpack_require__ (http://localhost:8101/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8101/build/main.js:181423:70)
    at __webpack_require__ (http://localhost:8101/build/main.js:20:30)
    at Object.defineProperty.value (http://localhost:8101/build/main.js:66:18)
    at http://localhost:8101/build/main.js:69:10

**Comment by emiyalee1005** [comment]
yeah,it miss sourceMap files and i add it in new router version(1.4.2).

**Comment by numerized** [comment]
I'm now evaluating the Ionic2 deeplinker. If it fails I'll come back to your project dude..Thanks
